---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redmine
  namespace: kubepost
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-app-redmine
  template:
    metadata:
      labels:
        app: my-app-redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: testuser
          - name: REDMINE_DB_DATABASE
            value: testdatabase		  
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: POSTGRES_PASSWORD
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: my-secret-redmine
                key: REDMINE_PASSWORD
